// fp_mult.v

// Generated using ACDS version 17.1 240

`timescale 1 ps / 1 ps
module fp_mult (
		input  wire [31:0] dataa,      //      a.a
		input  wire [31:0] datab,      //      b.b
		input  wire        clock,    //    clk.clk
		input  wire [0:0]  clk_en,     //     en.en
		output wire [31:0] result       //      q.q
	);

	fp_mult_altera_fp_functions_171_z2kbsra fp_functions_0 (
		.clk    (clock),    //   input,   width = 1,    clk.clk
		.areset (0), //   input,   width = 1, areset.reset
		.en     (clk_en),     //   input,   width = 1,     en.en
		.a      (dataa),      //   input,  width = 32,      a.a
		.b      (datab),      //   input,  width = 32,      b.b
		.q      (result)       //  output,  width = 32,      q.q
	);

endmodule
